aliases:
  - 'server'
  - 'asthonia'
  - 'khavalon'
  - 'lobby'

menu:
  name: 'Server Selector' # MiniMessage does not work on this unfortunately
  size: 27
  fill:
    enabled: true
    material: 'BLACK_STAINED_GLASS_PANE'
  servers:
    1:
      slot: 11
      material: 'RED_STAINED_GLASS_PANE'
      name: '<gold>Khavalon'
      proxy-server-name: 'khavalon'
      lore:
        - ''
        - '<gray>Click to join the Khavalon server!'
    2:
      slot: 15
      material: 'PURPLE_STAINED_GLASS_PANE'
      name: '<dark_purple>Asthonia'
      proxy-server-name: 'asthonia'
      lore:
        - ''
        - '<gray>Click to join the Asthonia server!'
