aliases:
  - 'server'
  - 'asthonia'
  - 'khavalon'
  - 'lobby'

playercount-update-time: 10 # seconds

menu:
  name: 'Server Selector' # MiniMessage does not work on this unfortunately
  size: 27
  fill:
    enabled: true
    material: 'BLACK_STAINED_GLASS_PANE'
  pinging: 'Pinging...' # Message to display while pinging servers
  servers:
    1:
      slot: 11
      material: 'RED_STAINED_GLASS_PANE'
      name: '<gold>Khavalon'
      proxy-server-name: 'khavalon'
      lore:
        - ''
        - '<gray>Player Count: %count%'
        - '<gray>Click to join the Khavalon server!'
    2:
      slot: 15
      material: 'PURPLE_STAINED_GLASS_PANE'
      name: '<dark_purple>Asthonia'
      proxy-server-name: 'asthonia'
      permission: 'server.asthonia'
      lore:
        - ''
        - '<gray>Player Count: %count%'
        - 'hasperm:<gray>Click to join the Asthonia server!'
        - 'noperm:<red>You do not have permission to access this server'
